/**
 * Win32 OS - Asset Declarations
 * Auto-generated by convert_assets.py
 */

#ifndef ASSETS_H
#define ASSETS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FONTS ============
LV_FONT_DECLARE(CodeProVariable);

// ============ APP ICONS (48x48) ============
LV_IMG_DECLARE(img_2048);  // 48x48
LV_IMG_DECLARE(img_accessibility);  // 32x32
LV_IMG_DECLARE(img_calculator);  // 48x48
LV_IMG_DECLARE(img_camera);  // 48x48
LV_IMG_DECLARE(img_clock);  // 48x48
LV_IMG_DECLARE(img_con);  // 48x48
LV_IMG_DECLARE(img_ethernet);  // 32x32
LV_IMG_DECLARE(img_explorer);  // 32x32
LV_IMG_DECLARE(img_file);  // 24x24
LV_IMG_DECLARE(img_flappy);  // 48x48
LV_IMG_DECLARE(img_folder);  // 48x48
LV_IMG_DECLARE(img_memory);  // 48x48
LV_IMG_DECLARE(img_microphone);  // 48x48
LV_IMG_DECLARE(img_minesweeper);  // 48x48
LV_IMG_DECLARE(img_my_computer);  // 48x48
LV_IMG_DECLARE(img_network);  // 32x32
LV_IMG_DECLARE(img_notepad);  // 48x48
LV_IMG_DECLARE(img_paint);  // 48x48
LV_IMG_DECLARE(img_personalization);  // 32x32
LV_IMG_DECLARE(img_photo);  // 24x24
LV_IMG_DECLARE(img_photoview);  // 48x48
LV_IMG_DECLARE(img_settings);  // 48x48
LV_IMG_DECLARE(img_snake);  // 48x48
LV_IMG_DECLARE(img_taskmgr);  // 48x48
LV_IMG_DECLARE(img_tetris);  // 48x48
LV_IMG_DECLARE(img_tictactoe);  // 48x48
LV_IMG_DECLARE(img_trashbinempty);  // 48x48
LV_IMG_DECLARE(img_trashbinfull);  // 48x48
LV_IMG_DECLARE(img_unkown);  // 24x24
LV_IMG_DECLARE(img_user);  // 32x32
LV_IMG_DECLARE(img_vscode);  // 48x48
LV_IMG_DECLARE(img_weather);  // 48x48

// ============ UI ELEMENTS ============
LV_IMG_DECLARE(img_logo);  // 80x80
LV_IMG_DECLARE(img_start_button);  // 64x64
LV_IMG_DECLARE(img_start_button11);  // 64x64
LV_IMG_DECLARE(img_start_buttonxp);  // 64x64
LV_IMG_DECLARE(img_windows_logo);  // 48x48

// ============ SYSTEM ICONS (20x20) ============
LV_IMG_DECLARE(img_bluetooth);  // 16x16
LV_IMG_DECLARE(img_information);  // 48x48
LV_IMG_DECLARE(img_warning);  // 16x16
LV_IMG_DECLARE(img_wifi);  // 16x16

// ============ WALLPAPERS (480x800) ============
LV_IMG_DECLARE(img_win10);  // 240x400
LV_IMG_DECLARE(img_win11);  // 240x400
LV_IMG_DECLARE(img_win7);  // 240x400
LV_IMG_DECLARE(img_win8);  // 240x400
LV_IMG_DECLARE(img_winvista);  // 240x400
LV_IMG_DECLARE(img_winxp);  // 240x400

// ============ FLAPPY BIRD GAME ASSETS ============
LV_IMG_DECLARE(img_flappy_background);  // 480x800
LV_IMG_DECLARE(img_flappy_pipe);  // 60x200

// ============ STARTUP ANIMATION (17 frames, RGB565) ============
#define STARTUP_FRAME_COUNT 17
#define STARTUP_FRAME_DELAY_MS 100  // ~10fps (slower for fewer frames)
extern const lv_image_dsc_t *startup_frames[STARTUP_FRAME_COUNT];

// Wallpaper count
#define WALLPAPER_COUNT 6

// Wallpaper info structure
typedef struct {
    const lv_image_dsc_t *image;
    const char *name;
} wallpaper_info_t;

extern const wallpaper_info_t wallpapers[];

#ifdef __cplusplus
}
#endif

#endif // ASSETS_H
