/**
 * Cyrillic Font Declaration
 * 
 * To use Cyrillic text, you need to:
 * 1. Install lv_font_conv: npm install -g lv_font_conv
 * 2. Run: python generate_cyrillic_font.py
 * 
 * Or use FreeType font rendering (requires CONFIG_LV_USE_FREETYPE=y)
 */

#ifndef FONT_CYRILLIC_H
#define FONT_CYRILLIC_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Declare the Cyrillic font (generated by lv_font_conv)
// LV_FONT_DECLARE(font_cyrillic_14);

// For now, use the built-in Montserrat font (ASCII only)
// To enable Cyrillic, generate the font using lv_font_conv

#ifdef __cplusplus
}
#endif

#endif // FONT_CYRILLIC_H
