#!/usr/bin/env python3
"""
Asset Converter for Win32 OS
Converts images to LVGL C arrays with proper sizing

Usage: python convert_assets.py
"""

import os
import sys
import re
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed!")
    print("Run: pip install Pillow")
    sys.exit(1)

# Configuration - sizes for each category
# OPTIMIZED: Smaller icons to save flash memory
SIZES = {
    'icons': (32, 32),           # App icons (was 48x48, saves ~55% per icon)
    'system': (16, 16),          # System tray icons (was 20x20)
    'ui': None,                  # Special handling
    'wallpapers': (240, 400),    # Half resolution for memory savings
    'flappybird': None,          # Special handling for game assets
}

# Icons that need larger size (desktop icons) - ALL app icons should be 48x48
LARGE_ICONS = [
    'my_computer', 'folder', 'trashbinempty', 'trashbinfull',
    'calculator', 'camera', 'weather', 'clock', 'settings', 'notepad',
    'photoview', 'flappy', 'information', 'debug', 'paint', 'con',
    'microphone', 'taskmgr', 'snake', 'vscode',
    # Game icons
    'tictactoe', '2048', 'tetris', 'memory', 'minesweeper'
]
LARGE_ICON_SIZE = (48, 48)  # Desktop icons stay 48x48

# Small icons for file browser (file types)
SMALL_ICONS = ['file', 'photo', 'unkown']
SMALL_ICON_SIZE = (24, 24)  # File type icons are smaller

# System icons that need larger size (for desktop use)
LARGE_SYSTEM_ICONS = ['information']
LARGE_SYSTEM_ICON_SIZE = (48, 48)

# Special sizes for UI elements
UI_SIZES = {
    'start_button': (64, 64),    # Vista orb (Win7)
    'start_button11': (64, 64),  # Win11 style
    'start_buttonxp': (64, 64),  # WinXP style
    'windows_logo': (48, 48),    # Windows logo
    'logo': (80, 80),            # WinESP32 logo for About page
}

# Flappy Bird game assets
FLAPPY_SIZES = {
    'pipe': (60, 200),           # Pipe sprite (will be flipped in code)
    'background': (480, 800),    # Full screen background
}

# Startup animation optimization
STARTUP_FRAME_SKIP = 4          # Take every Nth frame (68/4 = 17 frames)
STARTUP_FRAME_SIZE = (120, 160) # Smaller size
STARTUP_USE_RGB565 = True       # Use RGB565 instead of ARGB8888 (half size)

# Wallpaper optimization
WALLPAPER_USE_RGB565 = True     # Use RGB565 for wallpapers too

RAW_DIR = Path(__file__).parent / 'raw'
CONVERTED_DIR = Path(__file__).parent / 'converted'
OUTPUT_HEADER = Path(__file__).parent / 'converted' / 'assets.h'

def resize_image(img, size, keep_aspect=True):
    """Resize image to target size"""
    if img.mode != 'RGBA':
        img = img.convert('RGBA')
    
    if keep_aspect:
        ratio = min(size[0] / img.width, size[1] / img.height)
        new_size = (int(img.width * ratio), int(img.height * ratio))
        img = img.resize(new_size, Image.Resampling.LANCZOS)
        
        new_img = Image.new('RGBA', size, (0, 0, 0, 0))
        x = (size[0] - img.width) // 2
        y = (size[1] - img.height) // 2
        new_img.paste(img, (x, y), img if img.mode == 'RGBA' else None)
        return new_img
    else:
        return img.resize(size, Image.Resampling.LANCZOS)

def image_to_c_array(img, name, use_rgb565=False):
    """Convert image to LVGL C array"""
    if img.mode != 'RGBA':
        img = img.convert('RGBA')
    
    width, height = img.size
    pixels = list(img.getdata())
    
    if use_rgb565:
        # RGB565 format (2 bytes per pixel)
        cf_name = "LV_COLOR_FORMAT_RGB565"
        bytes_per_pixel = 2
        
        c_code = f"""// Auto-generated by convert_assets.py
// Image: {name}, Size: {width}x{height}, Format: RGB565

#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
"""
        data = []
        for r, g, b, a in pixels:
            # RGB565: RRRRRGGG GGGBBBBB
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            data.append(f"0x{rgb565 & 0xFF:02x}")
            data.append(f"0x{(rgb565 >> 8) & 0xFF:02x}")
    else:
        # ARGB8888 format (4 bytes per pixel)
        cf_name = "LV_COLOR_FORMAT_ARGB8888"
        bytes_per_pixel = 4
        
        c_code = f"""// Auto-generated by convert_assets.py
// Image: {name}, Size: {width}x{height}, Format: ARGB8888

#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
"""
        data = []
        for r, g, b, a in pixels:
            data.append(f"0x{b:02x}")
            data.append(f"0x{g:02x}")
            data.append(f"0x{r:02x}")
            data.append(f"0x{a:02x}")
    
    for i in range(0, len(data), 32):
        row = data[i:i+32]
        c_code += "    " + ", ".join(row) + ",\n"
    
    c_code += f"""}};

const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = {cf_name},
        .w = {width},
        .h = {height},
    }},
    .data_size = {width * height * bytes_per_pixel},
    .data = {name}_map,
}};
"""
    return c_code

def process_startup_frames():
    """Process startup animation frames with optimization"""
    startup_dir = RAW_DIR / 'startup'
    if not startup_dir.exists():
        print(f"  Startup directory not found: {startup_dir}")
        return []
    
    # Find all anim (N).png files
    frame_files = []
    for f in startup_dir.glob('anim (*).png'):
        match = re.search(r'anim \((\d+)\)\.png', f.name)
        if match:
            frame_num = int(match.group(1))
            frame_files.append((frame_num, f))
    
    frame_files.sort(key=lambda x: x[0])
    
    if not frame_files:
        print("  No animation frames found")
        return []
    
    print(f"  Found {len(frame_files)} frames, taking every {STARTUP_FRAME_SKIP}th")
    
    # Take every Nth frame
    selected_frames = [(num, path) for num, path in frame_files if num % STARTUP_FRAME_SKIP == 1]
    print(f"  Selected {len(selected_frames)} frames")
    
    results = []
    new_frame_num = 1
    
    for orig_num, img_path in selected_frames:
        try:
            img = Image.open(img_path)
            if img.mode != 'RGBA':
                img = img.convert('RGBA')
            
            # Resize to smaller size
            if STARTUP_FRAME_SIZE:
                img = img.resize(STARTUP_FRAME_SIZE, Image.Resampling.LANCZOS)
            
            width, height = img.size
            safe_name = f"img_startup_frame_{new_frame_num:02d}"
            
            c_code = image_to_c_array(img, safe_name, use_rgb565=STARTUP_USE_RGB565)
            
            output_file = CONVERTED_DIR / f"{safe_name}.c"
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(c_code)
            
            fmt = "RGB565" if STARTUP_USE_RGB565 else "ARGB8888"
            print(f"    Frame {new_frame_num:2d} (orig {orig_num:2d}): {width}x{height} {fmt}")
            results.append((safe_name, width, height, new_frame_num))
            new_frame_num += 1
            
        except Exception as e:
            print(f"    ERROR frame {orig_num}: {e}")
    
    if results:
        generate_startup_frames_list(results)
    
    return results

def generate_startup_frames_list(frames):
    """Generate C file with startup animation frames array"""
    frames.sort(key=lambda x: x[3])
    
    c_code = f"""// Auto-generated startup animation frames
// {len(frames)} frames at ~30fps = ~{len(frames)/30:.1f} seconds animation
// Optimized: RGB565, {STARTUP_FRAME_SIZE[0]}x{STARTUP_FRAME_SIZE[1]}

#include "assets.h"

"""
    
    for name, w, h, num in frames:
        c_code += f"LV_IMG_DECLARE({name});\n"
    
    c_code += f"""
const lv_image_dsc_t *startup_frames[STARTUP_FRAME_COUNT] = {{
"""
    
    for name, w, h, num in frames:
        c_code += f"    &{name},\n"
    
    c_code += "};\n"
    
    output_file = CONVERTED_DIR / "startup_frames.c"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(c_code)
    print(f"  Generated: {output_file.name}")

def process_flappybird_assets():
    """Process Flappy Bird game assets"""
    flappy_dir = RAW_DIR / 'flappybird'
    if not flappy_dir.exists():
        print(f"  Flappy Bird directory not found: {flappy_dir}")
        return []
    
    results = []
    
    for img_path in sorted(flappy_dir.glob('*')):
        if img_path.suffix.lower() not in ['.png', '.jpg', '.jpeg']:
            continue
        
        print(f"  Processing: {img_path.name}")
        
        try:
            img = Image.open(img_path)
            original_size = f"{img.width}x{img.height}"
            
            name_base = img_path.stem.lower()
            safe_name = f"img_flappy_{name_base}"
            
            # Get target size
            size = FLAPPY_SIZES.get(name_base)
            
            if size:
                # Resize without keeping aspect for game assets
                if img.mode != 'RGBA':
                    img = img.convert('RGBA')
                img = img.resize(size, Image.Resampling.LANCZOS)
            
            # Use RGB565 for background (large), ARGB8888 for pipe (needs transparency)
            use_rgb565 = (name_base == 'background')
            c_code = image_to_c_array(img, safe_name, use_rgb565=use_rgb565)
            
            output_file = CONVERTED_DIR / f"{safe_name}.c"
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(c_code)
            
            fmt = "RGB565" if use_rgb565 else "ARGB8888"
            print(f"    {original_size} -> {img.width}x{img.height} {fmt} => {output_file.name}")
            results.append((safe_name, img.width, img.height, 'flappybird'))
            
        except Exception as e:
            print(f"    ERROR: {e}")
    
    return results

def process_directory(subdir, target_size):
    """Process all images in a directory"""
    input_dir = RAW_DIR / subdir
    if not input_dir.exists():
        print(f"  Directory not found: {input_dir}")
        return []
    
    # Special handling for flappybird
    if subdir == 'flappybird':
        return process_flappybird_assets()
    
    results = []
    for img_path in sorted(input_dir.glob('*')):
        if img_path.suffix.lower() not in ['.png', '.jpg', '.jpeg', '.bmp', '.gif']:
            continue
        
        if subdir == 'startup' and 'anim' in img_path.name.lower():
            continue
        
        print(f"  Processing: {img_path.name}")
        
        try:
            img = Image.open(img_path)
            original_size = f"{img.width}x{img.height}"
            
            name_base = img_path.stem.lower()
            
            if subdir == 'ui':
                size = UI_SIZES.get(name_base, (img.width, img.height))
            elif subdir == 'icons':
                # Different sizes for different icon types
                if name_base in LARGE_ICONS:
                    size = LARGE_ICON_SIZE
                elif name_base in SMALL_ICONS:
                    size = SMALL_ICON_SIZE
                else:
                    size = target_size
            elif subdir == 'system':
                # Some system icons need to be larger for desktop use
                if name_base in LARGE_SYSTEM_ICONS:
                    size = LARGE_SYSTEM_ICON_SIZE
                else:
                    size = target_size
            else:
                size = target_size
            
            if size:
                keep_aspect = (subdir in ['icons', 'system', 'ui'])
                img = resize_image(img, size, keep_aspect=keep_aspect)
            
            safe_name = name_base.replace('-', '_').replace(' ', '_').replace('(', '').replace(')', '')
            safe_name = f"img_{safe_name}"
            
            # Use RGB565 for wallpapers to save memory
            use_rgb565 = (subdir == 'wallpapers' and WALLPAPER_USE_RGB565)
            c_code = image_to_c_array(img, safe_name, use_rgb565=use_rgb565)
            
            output_file = CONVERTED_DIR / f"{safe_name}.c"
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(c_code)
            
            fmt = "RGB565" if use_rgb565 else "ARGB8888"
            print(f"    {original_size} -> {img.width}x{img.height} {fmt} => {output_file.name}")
            results.append((safe_name, img.width, img.height, subdir))
            
        except Exception as e:
            print(f"    ERROR: {e}")
    
    return results

def generate_header(all_assets, startup_frames):
    """Generate main header file"""
    header = """/**
 * Win32 OS - Asset Declarations
 * Auto-generated by convert_assets.py
 */

#ifndef ASSETS_H
#define ASSETS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FONTS ============
LV_FONT_DECLARE(CodeProVariable);

"""
    
    categories = {}
    for name, w, h, cat in all_assets:
        if cat not in categories:
            categories[cat] = []
        categories[cat].append((name, w, h))
    
    cat_names = {
        'icons': 'APP ICONS (48x48)',
        'ui': 'UI ELEMENTS',
        'system': 'SYSTEM ICONS (20x20)',
        'wallpapers': 'WALLPAPERS (480x800)',
        'flappybird': 'FLAPPY BIRD GAME ASSETS',
    }
    
    for cat in ['icons', 'ui', 'system', 'wallpapers', 'flappybird']:
        if cat in categories:
            header += f"// ============ {cat_names.get(cat, cat.upper())} ============\n"
            for name, w, h in categories[cat]:
                header += f"LV_IMG_DECLARE({name});  // {w}x{h}\n"
            header += "\n"
    
    if startup_frames:
        header += f"// ============ STARTUP ANIMATION ({len(startup_frames)} frames, RGB565) ============\n"
        header += f"#define STARTUP_FRAME_COUNT {len(startup_frames)}\n"
        header += f"#define STARTUP_FRAME_DELAY_MS 100  // ~10fps (slower for fewer frames)\n"
        header += f"extern const lv_image_dsc_t *startup_frames[STARTUP_FRAME_COUNT];\n\n"
    
    if 'wallpapers' in categories:
        header += f"// Wallpaper count\n"
        header += f"#define WALLPAPER_COUNT {len(categories['wallpapers'])}\n\n"
        header += """// Wallpaper info structure
typedef struct {
    const lv_image_dsc_t *image;
    const char *name;
} wallpaper_info_t;

extern const wallpaper_info_t wallpapers[];

"""
    
    header += """#ifdef __cplusplus
}
#endif

#endif // ASSETS_H
"""
    
    with open(OUTPUT_HEADER, 'w', encoding='utf-8') as f:
        f.write(header)
    
    if 'wallpapers' in categories:
        generate_wallpapers_list(categories['wallpapers'])

def generate_wallpapers_list(wallpapers):
    """Generate C file with wallpaper list"""
    c_code = """// Auto-generated wallpaper list
#include "assets.h"

const wallpaper_info_t wallpapers[WALLPAPER_COUNT] = {
"""
    for name, w, h in wallpapers:
        display_name = name.replace('img_', '').replace('_', ' ').title()
        c_code += f'    {{ &{name}, "{display_name}" }},\n'
    c_code += "};\n"
    
    output_file = CONVERTED_DIR / "wallpapers_list.c"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(c_code)

def main():
    print("=" * 50)
    print("Win32 OS Asset Converter (Optimized)")
    print("=" * 50)
    
    CONVERTED_DIR.mkdir(exist_ok=True)
    
    # Clean old startup frames
    for old_file in CONVERTED_DIR.glob('img_startup_frame_*.c'):
        old_file.unlink()
    
    all_assets = []
    startup_frames = []
    
    for subdir, size in SIZES.items():
        print(f"\n[{subdir.upper()}]")
        results = process_directory(subdir, size)
        all_assets.extend(results)
    
    print(f"\n[STARTUP ANIMATION - OPTIMIZED]")
    startup_frames = process_startup_frames()
    
    if all_assets or startup_frames:
        generate_header(all_assets, startup_frames)
        total = len(all_assets) + len(startup_frames)
        print(f"\n{'=' * 50}")
        print(f"✅ Converted {total} assets!")
        print(f"   - Regular: {len(all_assets)}")
        print(f"   - Startup frames: {len(startup_frames)} (was 68)")
        
        # Calculate size savings
        old_size = 68 * 240 * 320 * 4  # Old: 68 frames, ARGB8888
        new_size = len(startup_frames) * STARTUP_FRAME_SIZE[0] * STARTUP_FRAME_SIZE[1] * 2  # RGB565
        print(f"   - Animation size: {new_size/1024/1024:.1f}MB (was {old_size/1024/1024:.1f}MB)")
    
    print("=" * 50)

if __name__ == '__main__':
    main()
